### ISSUE TITLE
Fix over-ambitious email obfuscator

### ISSUE THREAD

**Issue by treyhunner** [airpair/creating-a-custom-bootstrap-build-with-scss#2]
@jkresner looks like a bug in the way email addresses are obfuscated on Airpair

![selection_436](https://cloud.githubusercontent.com/assets/285352/8153073/e75effda-12db-11e5-85fa-6e1269bde501.png)

**Comment by jkresner** [comment]
I wonder if this has to do with cloudflare ...

**Comment by jkresner** [comment]
Can you post here https://github.com/airpair/airpair-com-v1-issue-tracker/issues

thanks!!

**Comment by treyhunner** [comment]
Done
